server:
  port: 9100

bot:
  name:
  token:
  adminId:
  chat-interval: 60000
  max-messages: 14
  caption-length: 1024

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    drop-first: false

  cache:
    cache-names: division

logging:
  level:
    org.springframework: ERROR
    ru.veselov: DEBUG
    org.hibernate: ERROR
    #pattern:
    # console: "%magenta(%d{yyyy-MM-dd HH:mm:ss}) [%yellow(%thread)] %highlight(%-5level) %green(%logger{36}): %msg%n"
    #file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}: %msg%n"