server:
  port:

bot:
  name:
  token:
  adminId:
  chat-interval: 60000
  max-messages: 14
  caption-length: 1024

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    drop-first: false

  cache:
    cache-names: division

logging:
  level:
    org.springframework: INFO
    ru.veselov: DEBUG