server.name: kibana
server.host: "0.0.0.0"
server.publicBaseUrl: "http://localhost:5601"
monitoring.ui.container.elasticsearch.enabled: true #metrics
elasticsearch.hosts: [ "http://elasticsearch:9200" ]

elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_PASS}

#uIcu38g3QWH2yG0nKxAz for logstash